version: '3'
services:
  redis_server:
    image: 'redis'
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
