# Base Image
FROM node:16-alpine

# Specifies folder to be mounted
WORKDIR '/app'

# Copy files from host to container
COPY package.json .
RUN npm install
COPY . .

# Defaults command to run when container is started
CMD ["npm", "run", "dev"]